### ISSUE TITLE
Support changes to sublime-syntax from Sublime Text `Build 4075`

### ISSUE THREAD

**Issue by jrappen** [trishume/syntect#323]
#### Changes from `Build 4075`

* [x] hidden file extensions
    * [x] `hidden_file_extensions`(addressed by #419)
* [x] sublime-syntax v2
    * [x] `version: 2`
        * [x] set + meta_content_scope (addressed by #610)
        * [x] multiple push + clear_scopes (addressed by #610)
        * [x] embed_scope replacement (addressed by #612)
        * [x] set + clear_scopes (addressed by #612)
        * [x] embed escape meta scopes (addressed by #612)
* [x] inheritance
    * [x] `extends` (string value) (addressed by #610)
    * [x] `extends` (string array value where all syntaxes themselves extend from the same base) (addressed by #612)
* [x] meta patterns:
    * [x] `meta_prepend` (addressed by #610)
    * [x] `meta_append` (addressed by #610)
* [x] match patterns:
    * [x] pop multiple contexts via `pop: 2` etc.
* [x] including an external prototype (addressed by #610)

#### Documentation

<https://www.sublimetext.com/docs/syntax.html#ver-dev>

**Comment by stefanobaghino** [comment]
It's quite nice to see some progress happening with #536! Thanks @jalil-salame!

I'm considering helping. Is there other work going on concerning this ticket apart from the aforementioned draft PR?

**Comment by jalil-salame** [comment]
> It's quite nice to see some progress happening with #536! Thanks @jalil-salame!
> 
> I'm considering helping. Is there other work going on concerning this ticket apart from the aforementioned draft PR?

I need to figure out why the tests are failing in #535 (this updates sublime packages to a newer version) before I can open #536 for review. If you check the comments on #535 you'll see where I'm stuck (I also don't have much time so helping hands will be useful).

**Comment by Keats** [comment]
Exciting, you're killing it @jalil-salame !

**Comment by stefanobaghino** [comment]
Since #536 seems to be stuck, I started having a look with #610.

**Comment by stefanobaghino** [comment]
Work continuing in https://github.com/trishume/syntect/pull/612 -- @jrappen re: including an external prototype -- isn't it handled by #610 already?

**Comment by stefanobaghino** [comment]
@jrappen I had a second look and I'm under the impression that "embed escape meta scopes" is also handled by #612, meaning that that would close this issue. Does that make sense?

**Comment by jrappen** [comment]
@stefanobaghino I wouldn't word it as #612 closing this issue as that PR only covers part of what is listed in the opening comment here and doing so might give the wrong impressions if you just close this issue via #612. Linking to here from there is fine obviously and makes sense.

I'd rather just link to all the different PRs from here and tick off the done items and close this issue once the list is complete.

**Comment by stefanobaghino** [comment]
> [@stefanobaghino](https://github.com/stefanobaghino) I wouldn't word it as [#612](https://github.com/trishume/syntect/pull/612) closing this issue as that PR only covers part of what is listed in the opening comment here and doing so might give the wrong impressions if you just close this issue via [#612](https://github.com/trishume/syntect/pull/612). Linking to here from there is fine obviously and makes sense.
> 
> I'd rather just link to all the different PRs from here and tick off the done items and close this issue once the list is complete.

Sorry for wording it in a way that lent itself to misunderstanding. I was just trying to understand if there was something else to work on for this ticket to be closed (other than what you mentioned in [your latest comment](https://github.com/trishume/syntect/pull/612#issuecomment-4054206566)). If that's the case, happy to work on that too.

**Comment by jrappen** [comment]
No need to be sorry, I just prefer explicit over implicit.

---

For syntaxes written for Sublime Text Build 4050+, there's still branch support missing. See #271.

With regards to what's left for syntax v2 support, I guess we covered everything here. This issue would close after #612 is done.

**Comment by FichteFoll** [comment]
Branching was added in the first ST4 build, i.e. 4050, several months before v2.

**Comment by stefanobaghino** [comment]
Nothing against closing this, but #612 should probably be merged to be consistent. 🙂 /cc @keith-hall

**Comment by jrappen** [comment]
Not sure what you're looking at...

<img width="915" height="380" alt="Image" src="https://github.com/user-attachments/assets/88cab97e-fe9f-42f4-8825-d8732d2a3267" />

**Comment by stefanobaghino** [comment]
I'm aware, but that was not the case at the time of writing.

**Comment by guille** [comment]
Looking forward to the hundreds of closed issues in the coming months when downstream consumers of syntect upgrade! Amazing stuff @stefanobaghino

**Comment by stefanobaghino** [comment]
@guille I'm looking forward to that as well. 🙂 Some patience will be necessary: the fixes required breaking changes and IIUC this means that before they can be shipped, all the pending items for 6.x need to be closed. I'm trying to understand with the maintainers whether my understanding is correct, and in that case I'd be happy to take care of that.
